### ISSUE TITLE
NoMethodError - undefined method `reverse_merge' for 30:Fixnum

### ISSUE THREAD

**Issue by jottr** [spilliton/randumb#34]
The line using randumb: 
```ruby
    users = User.where.not('users.avatar' => nil).order_by_rand(30)
````

```bash
$ rails --version
Rails 4.1.14.2

$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```
```
# ./Gemfile.lock
#...
    randumb (0.5.0)
      activerecord (>= 3.0.0)
      activesupport (>= 3.0.0)
      rake
#...
```

Trace:

```
NoMethodError - undefined method `reverse_merge' for 30:Fixnum:
  randumb (0.5.0) lib/randumb/relation.rb:79:in `build_order_scope'
  randumb (0.5.0) lib/randumb/relation.rb:67:in `order_by_rand'
  app/controllers/api/user_wishes_controller.rb:60:in `index'
  actionpack (4.1.14.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.14.2) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.14.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.14.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.14.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.14.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.14.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.14.2) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.14.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.14.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.14.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.14.2) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:690:in `call'
  bullet (5.0.0) lib/bullet/rack.rb:12:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.14.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.14.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.14.2) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  bugsnag (3.0.0) lib/bugsnag/rack.rb:33:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.14.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  rack-timeout (0.3.2) lib/rack/timeout/core.rb:125:in `block in call'
  rack-timeout (0.3.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
  rack-timeout (0.3.2) lib/rack/timeout/core.rb:124:in `call'
  activesupport (4.1.14.2) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/static.rb:84:in `call'
  font_assets (0.1.12) lib/font_assets/middleware.rb:29:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.14.2) lib/rails/engine.rb:514:in `call'
  railties (4.1.14.2) lib/rails/application.rb:144:in `call'
  /Users/jottr/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:155:in `handle'
  /Users/jottr/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:109:in `rescue in block (2 levels) in start'
  /Users/jottr/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:106:in `block (2 levels) in start'
  /Users/jottr/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `block in start'
  /Users/jottr/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `start'
  /Users/jottr/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
  /Users/jottr/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'



```

**Comment by jottr** [comment]
@spilliton is this project still maintained. I just realized that pull requests are not merged, and issues are not being addressed. 
Maybe you could give us a heads up if this should rather be forked?

**Comment by spilliton** [comment]
Thanks for reporting!  Will be looking into this this weekend hopefully :)

**Comment by spilliton** [comment]
This is because ```order_by_rand``` takes a hash as a param instead of an integer:

https://github.com/spilliton/randumb#usage

If yo need to limit, you can simply chain a limit scope on there like:

```ruby
users = User.where.not('users.avatar' => nil).order_by_rand.limit(30)
```

I would be nice if a clearer error was thrown for this though...I'll add something to help guide users in the future.  Thanks!

**Comment by spilliton** [comment]
https://github.com/spilliton/randumb/commit/3c495382206a74994d3c634d0c05b8bc75f74a01

:+1:
